blog/urls.py
# from django.conf.urls import url
# from . import views
#
# urlpatterns = [
#     url(r'^$', views.post_list, name='post_list'),
#     url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
#     url(r'^post/new/$', views.post_new, name='post_new'),
# 	url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
#
#     url(r'^directors/', views.directors_list, name = 'directors'),
# 	url(r'^director/(?P<pk>\d+)/$', views.director_detail, name='director_detail'),
# 	url(r'^film/(?P<pk>\d+)/$', views.film_detail, name='film_detail'),
#
#
#     url(r'^items/', views.items_list, name = 'items'),
#     url(r'^film_items/', views.film_items_list, name = 'film_items'),
#
#     url(r'^list/(?P<pk>\d+)/$', views.list, name='list'),
#
#
#
# ]

#from django.urls import include, path

from django.conf.urls import include, url
from django.urls import path


from . import views

urlpatterns = [

    url(r'adm/(?P<slug>[\w-]+)$', views.list_adm, name='list_adm'),
    url(r'(?P<slug>[\w-]+)$', views.list, name='list'),
    # url(r'$', views.lists, name='lists'),
    path('', views.lists, name='lists'),
    path('adm/', views.lists_adm, name='lists_adm'),

    # url('',  views.index, name='index' ),


    # (?P<slug>[\w-]+)/$
# url(r'lists/<slug:slug>/', views.list, name='list'),

#    path('lists/(?P<slug>[-\w]+)/$', views.list, name='list'),

]

filmbase/urls.py
#from django.urls import include, path
from django.conf.urls import include, url

from . import views

app_name = 'filmbase'

urlpatterns = [
    # url(r'^/$', views.searchkp, name='searchkp'),

    # url(r'^post/(?P<slug>.+)/$', views.post_detail, name='post_detail'),
    url(r'(?P<slug>[\w\-]+)$', views.film_detail, name='film_detail'),
    url(r'(?P<pk>\d+)', views.film_detail, name='film_detail'),
    # url(r'kp(?P<kp_id>\d+)', views.film_detail, name='film_detail'),

    # url(r'(?P<slug>[\w-]+)$', views.list, name='list'),

    url(r'^search/$', views.search, name='search'),
    url(r'^searching/$', views.searching, name='searching'),

]

blog/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.template.defaultfilters import slugify
from transliterate import translit
from django.utils.encoding import python_2_unicode_compatible

from filmbase.models import *
from images.models import *

# from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# @python_2_unicode_compatible
class Author (models.Model):
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    comment = models.CharField(max_length=100, blank=True)
    vk = models.CharField(max_length=40)
    def __str__(self):
        return self.name + ' ' + self.surname + '(' + self.comment + ')'


# @python_2_unicode_compatible
class List(models.Model):
    title = models.CharField(max_length=400)
    intro = models.TextField(blank = True)
    slug = models.SlugField(max_length=60, blank=True)
    fin_count = models.PositiveSmallIntegerField(blank = True, null = True)
    author = models.ForeignKey('Author', on_delete = models.SET_NULL, blank = True, null = True)
    finished = models.BooleanField(default = False)
    publish = models.BooleanField(default = True)
    numered = models.BooleanField(default = False)
    compact = models.BooleanField(default = False)

    elem_image =  models.ForeignKey('images.Image',  on_delete=models.SET_NULL, blank = True, null = True)


    def save(self, *args, **kwargs):
        # if not self.id:
        # Only set the slug when the object is created.
        self.slug = slugify(translit(self.title, 'ru', reversed=True))  # Or whatever you want the slug to use
        super(List, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog.views.list_pk', args=[str(self.slug)])

    def __str__(self):
        return self.title

class Section (models.Model):
    name =  models.CharField(max_length=100)
    owner = models.ForeignKey('List', on_delete = models.SET_NULL, blank = True, null = True)
    order = models.IntegerField(null = True, blank = True)
    def __str__(self):
        return self.name


class Film_List_Elem(models.Model):
    film = models.ForeignKey('filmbase.Film', on_delete=models.PROTECT)
    elem_image =  models.ForeignKey('images.Shot',  on_delete=models.PROTECT, blank = True, null = True)
    text = models.TextField(blank = True)
    order = models.IntegerField(null = True, blank = True)
    owner_list = models.ForeignKey('List', on_delete=models.PROTECT, null=True, blank=True, default=1)
    section = models.ForeignKey('Section', on_delete = models.SET_NULL, blank = True, null = True)
    maybe = models.BooleanField(default = False)
    to_drop = models.BooleanField(default = False)
    def __str__(self):
        string = ''
        if self.order:
            string = str(self.order)
        string+=str(self.film.title) + ' ' + self.owner_list.title
        return string


class Review(models.Model):
    title = models.CharField(max_length=400, blank = True, null = True)
    film = models.ForeignKey('filmbase.Film', on_delete=models.PROTECT)
    # text = models.TextField(blank = True)
    content = RichTextUploadingField(blank = True, null = True)
    extract = models.TextField(blank = True)
    author = models.ForeignKey('Author', on_delete = models.SET_NULL, blank = True, null = True)
    single_article = models.BooleanField(default = False)
    def __str__(self):
        return self.title


# class Author (models.Model):
#     name = models.CharField(max_length=30)
#     surname = models.CharField(max_length=30)
#     vk = models.CharField(max_length=40)

# from django.db import models
# from django.utils import timezone
# from django.utils.encoding import python_2_unicode_compatible
#
#
#
# class Post(models.Model):
#     author = models.ForeignKey('auth.User', on_delete=models.PROTECT)
#     title = models.CharField(max_length=200)
#     text = models.TextField()
#     created_date = models.DateTimeField(
#             default=timezone.now)
#     published_date = models.DateTimeField(
#             blank=True, null=True)
#
#     def publish(self):
#         self.published_date = timezone.now()
#         self.save()
#
#     def __str__(self):
#         return self.title
#
#
# @python_2_unicode_compatible
# class Director(models.Model):
#     name = models.CharField(max_length=120)
#     image = models.CharField(max_length=400, default = '', blank = True)
#
#     def __str__(self):
#         return self.name
#
# class Film(models.Model):
#     title = models.CharField(max_length=150)
#     image = models.CharField(max_length=400, default = '', blank = True)
#     director = models.ForeignKey('Director',on_delete=models.PROTECT, null = True, blank = True, )
#     year = models.PositiveIntegerField(null = True, blank = True)
#     videovk = models.CharField(max_length=400, null = True, blank = True)
#     material = models.TextField(blank=True)
#     kp_id = models.PositiveIntegerField(null = True, blank = True)
#
#     def __str__(self):
#         return self.title
#
# class Video(models.Model):
#     link  = models.CharField(max_length=150)
#     title = models.CharField(max_length=150)
#     film = models.ForeignKey('Film', on_delete=models.PROTECT, null = True, blank = True)
#     duration = models.PositiveIntegerField(null = True, blank = True)
#     hd = models.PositiveIntegerField(null = True, blank = True)
#     status = models.CharField(max_length=150, null = True, blank = True)
#
#     def __str__(self):
#         return self.title
#
# # LI_CHOICES = (
# #     ('D','Director'),
# #     ('F','Film'),
# # )
#
# # class List_Elem(models.Model):
# #     type_of_choice = models.CharField(max_length=1, choices = LI_CHOICES, default = 'D')
# #     director = models.ForeignKey('Director',null=True, blank = True)
# #     film = models.ForeignKey('Film', null=True, blank = True)
# #     #title = models.ForeignKey('Director', models.SET_NULL, null = True)
# #     text = models.TextField()
# #     order = models.IntegerField()
#
# class List(models.Model):
#     title = models.CharField(max_length = 400)
#     intro = models.TextField()
#
#     def __str__(self):
#         return self.title
#
#
# class Film_List_Elem(models.Model):
#     film = models.ForeignKey('Film', on_delete=models.PROTECT)
#     text = models.TextField()
#     order = models.IntegerField()
#     owner_list = models.ForeignKey('List',  on_delete=models.PROTECT, null = True, blank = True, default = 1)
#
#     def __str__(self):
#         return self.film.title
#
# class Inbox(models.Model):
#     film = models.ForeignKey('Film', on_delete=models.PROTECT)
#
#     #published_date
#
#
# # class Movie()
# #     title
# #     director
#

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

blog/views.py
# -*- coding: utf-8 -*-

import datetime
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.http import HttpResponseRedirect


# Create your views here.


def index(request):
    return HttpResponseRedirect('vk/top/')
    # return render(request, 'blog/index.html')


def lists(request):

    lists = List.objects.filter(publish=True)


    return render(request, 'blog/lists.html', {'lists': lists})


def lists_adm(request):
    lists = List.objects.filter(publish=False)
    for list in lists:
        total = Film_List_Elem.objects.filter(owner_list = list).exclude(maybe = True).exclude(to_drop = True).count()
        list.total = total
        list.maybes = Film_List_Elem.objects.filter(owner_list = list, maybe = True ).count()
        list.to_drop = Film_List_Elem.objects.filter(owner_list = list, to_drop  = True).count()


    return render(request, 'blog/lists_adm.html', {'lists': lists})

import requests, json

def list(request, slug):
    print ('list')
    type = request.GET.get('type', 'html')
    print (type)
    # # do processing

    print ('im here')
    cur_list = get_object_or_404(List, slug=slug)
    # print (slug)
    # print(cur_list)
    if cur_list.compact:
        type = 'compact'
    items = Film_List_Elem.objects.filter(owner_list=cur_list.pk).order_by('section').exclude(maybe = True)
    # items_all = Film_List_Elem.objects.all()
    for item in items:
        item.put_link = False
        if (item.film.videos()):
            item.put_link = True
        if not item.put_link:

            week_ago = timezone.now() - datetime.timedelta(days=7)
            if not item.film.last_kodik_search:
                print ('not searched')
                item.film.last_kodik_search = timezone.now() - datetime.timedelta(days=14)
                item.film.save()
                print ('2weeks setted')
            if item.film.last_kodik_search < week_ago:

                print ('last search was earlier')
                print(item.film.last_kodik_search, week_ago)
                item.film.last_kodik_search = timezone.now()
                item.film.save()
                print(item.film.last_kodik_search)
                kodik_link = 'https://kodikapi.com/search?token=6c4f14a88c532aa24b15287e39ecb68c&kinopoisk_id=' \
                             + str(item.film.kp_id) + '&camrip=false'
                print (kodik_link)
                response = requests.get(kodik_link)
                data = json.loads(response.text)['results']
                if data:
                    item.put_link = True
                    print (data)
                    item.film.kodik = True
                    item.film.save()
        if item.film.kodik == True:
                item.put_link = True


        else:
            print('no film')

    prev_section = ''
    for item in items:
        if item.section:
            now_section = item.section.name
        else:
            now_section = ''
        #
        if prev_section != now_section: #now_section:
            # print ('=', item.section)
            prev_section = now_section

    sorted_by_section = {}
    sections = Section.objects.filter(owner = cur_list)
    for section in sections:
        # print ('=',section)

        section_items = items.filter(section = section)
        if len(section_items)>0:
            sorted_by_section[section] = section_items

    print (sorted_by_section)
        # for section_item in  (section_items):
        #     print (section_item)
    #   #тут уже собрались все итемы секции - их я занесу в дикт

    # for itema in items_all:
    #     try:
    #         print(itema.elem_image.image.url)
    #     except:
    #         itema.elem_image = None
    #         itema.save()

    if type == 'html':
        return render(request, 'blog/list.html', {'list': cur_list, 'items': items})
    elif type == 'zen':
        return render(request, 'blog/list_zen.html', {'list': cur_list, 'items': items})
    elif type == 'compact':
        return render(request, 'blog/list_compact.html', {'list': cur_list, 'items': items, 'sorted_by_section': sorted_by_section})


def list_adm(request, slug):
    print ('list')
    type = request.GET.get('type', 'html')
    print (type)
    # # do processing

    print ('im here')
    cur_list = get_object_or_404(List, slug=slug)
    # print (slug)
    # print(cur_list)
    if cur_list.compact:
        type = 'compact'
    items = Film_List_Elem.objects.filter(owner_list=cur_list.pk).order_by('section').exclude(maybe = True).exclude(to_drop = True)
    # items_all = Film_List_Elem.objects.all()
    for item in items:
        if (item.film.videos()):
            item.put_link = True
    prev_section = ''
    for item in items:
        if item.section:
            now_section = item.section.name
        else:
            now_section = ''
        #
        if prev_section != now_section: #now_section:
            # print ('=', item.section)
            prev_section = now_section

    sorted_by_section = {}
    sections = Section.objects.filter(owner = cur_list)
    for section in sections:
        # print ('=',section)

        section_items = items.filter(section = section)
        if len(section_items)>0:
            sorted_by_section[section] = section_items

    print (sorted_by_section)
        # for section_item in  (section_items):
        #     print (section_item)
    #   #тут уже собрались все итемы секции - их я занесу в дикт

    # for itema in items_all:
    #     try:
    #         print(itema.elem_image.image.url)
    #     except:
    #         itema.elem_image = None
    #         itema.save()

    if type == 'html':
        return render(request, 'blog/list_adm.html', {'list': cur_list, 'items': items})
    # elif type == 'zen':
    #     return render(request, 'blog/list_zen.html', {'list': cur_list, 'items': items})
    # elif type == 'compact':
    #     return render(request, 'blog/list_compact.html', {'list': cur_list, 'items': items, 'sorted_by_section': sorted_by_section})



# from django.shortcuts import render, get_object_or_404, redirect
# from .models import Post
# from .forms import PostForm
#
# from django.shortcuts import render
# from django.utils import timezone
# from .models import * #Post, Director, List_Elem, Film_List_Elem
#
# def post_list(request):
#     posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
#     return render(request, 'blog/post_list.html', {'posts': posts})
#
# def post_detail(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#     return render(request, 'blog/post_detail.html', {'post': post})
#
# def post_new(request):
#     if request.method == "POST":
#         form = PostForm(request.POST)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user
#             post.published_date = timezone.now()
#             post.save()
#             return redirect('post_detail', pk=post.pk)
#     else:
#         form = PostForm()
#     return render(request, 'blog/post_edit.html', {'form': form})
#
# def post_edit(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#     if request.method == "POST":
#         form = PostForm(request.POST, instance=post)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user
#             post.published_date = timezone.now()
#             post.save()
#             return redirect('post_detail', pk=post.pk)
#     else:
#         form = PostForm(instance=post)
#     return render(request, 'blog/post_edit.html', {'form': form})
#
# #def post_dir(request, pk)
#
# def directors_list(request):
#     directors = Director.objects.all()
#     return render(request, 'blog/directors.html', {'directors':directors})
#
# def director_detail(request, pk):
#     director = get_object_or_404(Director, pk=pk)
#     return render(request, 'blog/director_detail.html', {'director': director})
#
# def film_detail(request, pk):
#     film = get_object_or_404(Film, pk=pk)
#     video = get_object_or_404(Video, film=film)
#     return render(request, 'blog/film_detail.html', {'film': film, 'video': video})
#
# def items_list(request):
#     items = List_Elem.objects.all()
#     return render(request, 'blog/items.html', {'items':items})
#
# def film_items_list(request):
#     items = Film_List_Elem.objects.all()
#     return render(request, 'blog/film_items.html', {'items':items})
#
# def list(request, pk):
#     cur_list = get_object_or_404(List, pk=pk)
#     items = Film_List_Elem.objects.filter(owner_list = pk)
#     return render(request, 'blog/list.html', {'list': cur_list, 'items':items})

blog/templates/blog/list.html
{% extends 'blog/base.html' %}
{% load my_substract %}

{% block title %}{{list.title}}{% endblock %}

{% block content %}



<a href="http://vk.com/share.php?url=http://drugoekino.top/lists/{{list.slug}}"

   target="_blank" rel="nofollow">
   поделиться ВК
</a>

		<h1>{{list.title}}</h1>
		<br>
		{% if list.elem_image.image %}
			<img src = "{{list.elem_image.image.url}}" width = 100%> <br> <br>
		{% endif%}
		{{list.intro|linebreaks}}
		{% for item in items %}
			<div class = "post">
				<h2>
					{%if item.put_link or item.film.kodik%}
						<a href="{% url 'filmbase:film_detail' item.film.slug %}">
					{%endif %}

					{%if list.numered%}
					{{list.fin_count|my_substract:forloop.counter0}}.
											{%endif%}
					{{item.film.title}} /
					{%if item.film.title_en%}
						{{item.film.title_en}} /
					{%endif%}
					{{item.film.director}} {{item.film.year}}</h2>


				{% if  item.elem_image %}
				<img src = "{{item.elem_image.image.url}}" width = 100%> <br> <br>
				{% elif item.film.image %}
				<img src = "{{item.film.image}}" width = 100%> <br> <br>
				{% elif item.film.first_image %}
				<img src = "{{item.film.first_image.image.url}}" width = 100%> <br> <br>

				{%endif%}
				</a>


				<p>{{item.text|linebreaks}}</p>
		    	<!--{#<a href="{% url 'filmbase.film_detail' pk=item.film.pk %}">страница фильма</a>#}-->
				{%if item.put_link or item.film.kodik%}
					<a href="{% url 'filmbase:film_detail' item.film.slug %}">страница фильма «{{item.film.title}}», смотреть онлайн</a>
				{%endif%}
		    </div>
			<div align = center>***</div>
		{% endfor %}
<a href="http://vk.com/share.php?url=http://drugoekino.top/lists/{{list.slug}}"

   target="_blank" rel="nofollow">
	<br><br>
	<b>поделиться</b> этим постом <b>ВКонтакте</b>
</a>

<br><br>
{% if list.author %}
<i>Автор текста:</i> <a href = https://vk.com/{{list.author.vk}}>{{list.author.name}} {{list.author.surname}}</a>
<br>
{% endif %}

<div align = center>
	<br>
	{%if list.finished is False%}
	<b>Продолжение следует... </b>
	{%endif%}
	<br>
	Подпишитесь на рассылку, для уведомлений о новых публикациях! </div>



{% endblock %}

blog/templates/blog/list_adm.html
{% extends 'blog/base.html' %}
{% load my_substract %}
{% load humanize %}

{% block title %}{{list.title}}{% endblock %}

{% block content %}

list adm

<a href="http://vk.com/share.php?url=http://drugoekino.top/lists/{{list.slug}}"

   target="_blank" rel="nofollow">
   поделиться ВК
</a>

	{{list.title}}

		{{list.intro|linebreaks}}

<table >
		{% for item in items %}
        <tr>


            <td><b>{{item.film.rating | floatformat }}</b>  </td>
            <td width = 10% align = right style="padding:5px"><i>{{item.film.votes | intcomma}}</i> </td>
            <td>

					{%if list.numered%}
					({{list.fin_count|my_substract:forloop.counter0}}.
											{%endif%})
					{{item.film.title | truncatechars:25}} /
					{%if item.film.title_en%}
						{{item.film.title_en | truncatechars:25}} /
					{%endif%}
					{{item.film.director | truncatechars:15}} {{item.film.year}}

            </td>

</tr>



		{% endfor %}
</table>

<br><br>
{% if list.author %}
<i>Автор текста:</i> <a href = https://vk.com/{{list.author.vk}}>{{list.author.name}} {{list.author.surname}}</a>
<br>
{% endif %}

<div align = center>
	<br>
	{%if list.finished is False%}
	<b>Продолжение следует... </b>
	{%endif%}
	<br>
	Подпишитесь на рассылку, для уведомлений о новых публикациях! </div>



{% endblock %}

blog/templates/blog/list_compact.html
{% extends 'blog/base.html' %}
{% load my_substract %}

{% block title %}{{list.title}}{% endblock %}

{% block content %}



<a href="http://vk.com/share.php?url=http://drugoekino.top/lists/{{list.slug}}"

   target="_blank" rel="nofollow">
   поделиться ВК


</a>


		<h1>{{list.title}}</h1>
		{{list.intro}}
		{% if sorted_by_section%}
		{% for section, section_items in sorted_by_section.items%}
			<h2>{{section}}</h2>

			{% for item in section_items%}
				<div>
					<!--class = "post"-->
					<!--тут надо проверить - есть ли секции-->


					<!--{%if item.put_link %}-->
						<a href="{% url 'filmbase:film_detail' item.film.pk %}">
					<!--{%endif%}-->
						{%if list.numered%}
							{{list.fin_count|my_substract:forloop.counter0}}.
						{%endif%}

						{{item.film.title}}
						{%if item.film.title_en%}/ {{item.film.title_en}}{%endif%}
					<!--{% if item.put_link %}-->
						</a>
					<!--{%endif%}-->
					/ {{item.film.director}}  {{item.film.year}}



						<!--{% if  item.elem_image %}-->
						<!--<img src = "{{item.elem_image.image.url}}" width = 100%> <br> <br>-->
						<!--{% elif item.film.image %}-->
						<!--<img src = "{{item.film.image}}" width = 100%> <br> <br>-->
						<!--{%endif%}-->



					<p>{{item.text|linebreaks}}</p>
					<!--{#<a href="{% url 'filmbase.film_detail' pk=item.film.pk %}">страница фильма</a>#}-->
					<!--<a href="{% url 'filmbase:film_detail' item.film.pk %}">страница фильма, смотреть онлайн</a>-->
			</div>
			{% endfor %}
		{% endfor %}
		{% else %}
<!--список без секция-->
			{% for item in items%}
				<div>
					{%if item.put_link == True%}
					<a href="{% url 'filmbase:film_detail' item.film.slug %}">
					{%endif%}
						{%if list.numered%}
							{{list.fin_count|my_substract:forloop.counter0}}.
						{%endif%}
						{{item.film.title}}
						{%if item.film.title_en%}/ {{item.film.title_en}}{%endif%}
					{%if item.put_link %}
					</a>
					{%endif%}
					/ {{item.film.director}}  {{item.film.year}}



					<p>{{item.text|linebreaks}}</p>
			</div>
			{% endfor %}
		{% endif %}

		<!--{% for item in items %}-->
			<!--<div>-->
				<!--&lt;!&ndash;class = "post"&ndash;&gt;-->
				<!--&lt;!&ndash;тут надо проверить - есть ли секции&ndash;&gt;-->


				<!--<a href="{% url 'filmbase:film_detail' item.film.pk %}">-->
					<!--{%if list.numered%}-->
						<!--{{list.fin_count|my_substract:forloop.counter0}}.-->
					<!--{%endif%}-->
					<!--{{item.film.title}}-->
					<!--{%if item.film.title_en%}/ {{item.film.title_en}}{%endif%}-->
				<!--</a>-->
				<!--/ {{item.film.director}}  {{item.film.year}}-->



					<!--&lt;!&ndash;{% if  item.elem_image %}&ndash;&gt;-->
					<!--&lt;!&ndash;<img src = "{{item.elem_image.image.url}}" width = 100%> <br> <br>&ndash;&gt;-->
					<!--&lt;!&ndash;{% elif item.film.image %}&ndash;&gt;-->
					<!--&lt;!&ndash;<img src = "{{item.film.image}}" width = 100%> <br> <br>&ndash;&gt;-->
					<!--&lt;!&ndash;{%endif%}&ndash;&gt;-->



				<!--<p>{{item.text|linebreaks}}</p>-->
		    	<!--&lt;!&ndash;{#<a href="{% url 'filmbase.film_detail' pk=item.film.pk %}">страница фильма</a>#}&ndash;&gt;-->
				<!--&lt;!&ndash;<a href="{% url 'filmbase:film_detail' item.film.pk %}">страница фильма, смотреть онлайн</a>&ndash;&gt;-->
		<!--</div>-->
		<!--{% endfor %}-->
<br>
<a href="http://vk.com/share.php?url=http://drugoekino.top/lists/{{list.slug}}"

   target="_blank" rel="nofollow">
	<b>поделиться</b> этим постом <b>ВКонтакте</b>
</a>

<br><br>
{% if list.author %}
<i>Автор текста:</i> <a href = vk.com/{{list.author.vk}}>{{list.author.name}} {{list.author.surname}}</a>
<br>
{% endif %}

<div align = center>
	<br>
	{%if list.finished is False%}
	<b>Список дополняется... </b>
	{%endif%}
	<br>
	Подпишитесь на рассылку, чтобы не пропустить обновления! </div>



{% endblock %}

blog/templates/blog/list_zen.html
{% extends 'blog/base.html' %}
{% load my_substract %}

{% block title %}{{list.title}}{% endblock %}

{% block content %}



<a href="http://vk.com/share.php?url=http://drugoekino.top/lists/{{list.slug}}"

   target="_blank" rel="nofollow">
   поделиться ВК
</a>


		{% for item in items %}
		{{item.film.title}} ({{item.film.year}}) /
		{% endfor%}

		{% for item in items %}
		{{item.film.title}} |  
		{% endfor%}


		<h1>{{list.title}}</h1>
		{{list.intro}}
		{% for item in items %}
			<div class = "post">
				<h2>


					<a href = http://127.0.0.1:8000/admin/blog/film_list_elem/{{item.id}}/change/> админка</a>
					<br>

										<a href="{% url 'filmbase:film_detail' item.film.pk %}">

					{{list.fin_count|my_substract:forloop.counter0}}.
					{{item.film.title}} / {{item.film.director}} / {{item.film.year}}</h2>

				<img src = "{{item.film.image}}"> <br> <br>
</a>
				<p>{{item.text|linebreaks}}</p>
		    	<!--{#<a href="{% url 'filmbase.film_detail' pk=item.film.pk %}">страница фильма</a>#}-->
				<!--<a href="{% url 'filmbase:film_detail' item.film.pk %}">страница фильма, смотреть онлайн</a>-->
		    </div>
		{% endfor %}


<a href="http://vk.com/share.php?url=http://drugoekino.top/lists/{{list.slug}}"

   target="_blank" rel="nofollow">
	поделиться ВК
</a>

<br>
<br>

<div align = center> <b>Продолжение следует... </b><br> Подпишитесь, чтобы получить уведомление о новых публикациях! </div>



{% endblock %}

blog/templates/blog/lists.html
{% extends 'blog/base.html' %}

{% block content %}

		{% for list in lists%}
		{%if list.publish == True%}
			<p>
				<a href = {{list.slug}}>{{list}}</a>
		    </p>
		{%endif%}
		{% endfor %}
{% endblock %}

blog/templates/blog/lists_adm.html
{% extends 'blog/base.html' %}

{% block content %}

lists adm
		{% for list in lists%}

			<p>
				<a href = {{list.slug}}>{{list}}{{list.total}} + {{list.to_drop}} + {{list.maybes}}</a>
		    </p>
		{% endfor %}
{% endblock %}